---
- name: "Directory Exists | {{ postgresql_backup_path }}"
  file:
    state: directory
    path: "{{ postgresql_backup_path }}"
    owner: "{{ postgresql_user }}"
    group: wcadmin
    mode: 0775
  when: postgresql_backup_enabled
  tags:
    - directory-structure
    - postgres
    - backup

- name: Setup Automated Backups
  sudo: True
  sudo_user: postgres
  cron:
    name: postgres-backup
    special_time: "{{ postgresql_backup_frequency }}"
    job: "/usr/bin/pg_dump {{ database_name | default(project) }} | /usr/bin/7z a -si {{ postgres_backup_path }}/backup-`/bin/date +\\%Y\\%m\\%d\\%H`.7z"
  when: postgresql_backup_enabled
  tags:
    - postgres
    - backup
    - using-cron
