---
- name: Configure | postgres | listen_address
  lineinfile:
    state: present
    dest: /etc/postgresql/9.3/main/postgresql.conf
    regexp: '^#* *listen_addresses ='
    line: "listen_addresses = '*'"
  notify: Reload Service | postgres
  tags:
    - networking
  when: postgres_accepts_external_connections

- name: Configure | postgres | listen_address
  lineinfile:
    state: present
    dest: /etc/postgresql/9.3/main/pg_hba.conf
    regexp: "^#* *host {{ database.name | default(project) }}"
    line: "host {{ database.name | default(project) }} {{ database.username | default(project) }} 0.0.0.0/0 md5"
  notify: Reload Service | postgres
  tags:
    - networking
  when: postgres_accepts_external_connections
