---
- name: Install Packages | apt
  apt:
    state: latest
    pkg: "{{ item }}"
  with_items:
    - postgresql-client
  when: postgres_client

- name: Install Packages | apt
  apt:
    state: latest
    pkg: "{{ item }}"
  with_items:
    - postgresql
  when: postgres_server

- name: Create Database User
  postgresql_user:
    state: present
    name: "{{ database.username | default(project) }}"
    password: "{{ database.password | mandatory }}"
    role_attr_flags: CREATEDB
  when: postgres_server

- name: Service Stopped | postgres
  service:
    state: stopped
    name: postgresql
  when: postgres_server
  tags:
    - disruptive
