---
- name: Install Packages | apt
  apt:
    state: latest
    pkg: "{{ item }}"
  with_items:
    - postgresql-client
  when: postgres_client

- name: Install Packages | apt
  apt:
    state: latest
    pkg: "{{ item }}"
  with_items:
    - postgresql
    - postgresql-server-dev-all
    - python-dev
  when: postgres_server

- name: Install Packages | pip
  pip:
    state: latest
    name: "{{ item }}"
  with_items:
    - psycopg2
  when: postgres_server

- name: Install Packages | apt
  apt:
    state: latest
    pkg: "{{ item }}"
  with_items:
    - p7zip-full
  when: postgres_backup_enabled
  tags:
    - p7zip
    - backup

- name: Create Database User
  postgresql_user:
    state: present
    name: "{{ database_username | default(project) }}"
    password: "{{ database_password | mandatory }}"
    db: template1
    priv: CONNECT
#    role_attr_flags: SUPERUSER
  when: postgres_server
  sudo_user: postgres

- name: Create Database
  postgresql_db:
    state: present
    name: "{{ database_name | default(project) }}"
    owner: "{{ database_username | default(project) }}"
  when: postgres_server
  sudo_user: postgres

- name: Create Database User
  postgresql_user:
    state: present
    name: "{{ database_username | default(project) }}"
    password: "{{ database_password | mandatory }}"
    db: "{{ database_name | default(project) }}"
    priv: ALL
    role_attr_flags: CREATEDB
  when: postgres_server
  sudo_user: postgres

- name: Service Stopped | postgres
  service:
    state: stopped
    name: postgresql
  when: postgres_server
  tags:
    - disruptive
