---
- name: "Directory Exists | {{ postgres_runtime_root }}"
  file:
    state: directory
    path: "{{ postgres_runtime_root }}"
    owner: "{{ postgres_user }}"
    group: wcadmin
    mode: 0775
  tags:
    - directory-structure
    - runtime-data
    - postgres

- name: Configure | postgres | pidfile
  lineinfile:
    state: present
    dest: /etc/postgresql/9.3/main/postgresql.conf
    regexp: '^#*external_pid_file'
    line: "external_pid_file = '{{ postgres_pidfile_path }}'"
  notify: Reload Service | postgres
  tags:
    - pidfile
    - service
