---
- name: "Directory Exists | {{ postgres_runtime_root }}"
  file:
    state: directory
    path: "{{ postgres_runtime_root }}"
    owner: "{{ postgres_user }}"
    group: wcadmin
    mode: 0775
  tags:
    - directory-structure
    - runtime-data
    - postgres

- name: Upload Config | monit | postgres
  template:
    src: etc/monit/conf.d/postgres
    dest: /etc/monit/conf.d/postgres
  notify: Reload Service | monit
  tags:
    - monit

- name: Trigger All Callbacks
  meta: flush_handlers

- name: Configure | postgres | pidfile
  lineinfile:
    state: present
    dest: /etc/postgresql/9.3/main/postgresql.conf
    regexp: '^#*external_pid_file'
    line: "external_pid_file = '{{ postgres_pidfile_path }}'"
  notify: Reload Service | postgres
  tags:
    - pidfile
    - service

- name: Confirm Monitoring | postgres
  monit:
    state: present
    name: postgres
  tags:
    - monit
